version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.24.0
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    ports:
      - 8010:80
      #- 443:80
    volumes:
      #- ./ssl/keys/:/ssl/
      - ./vw-data:/data

# https://hub.docker.com/r/vaultwarden/server